deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
# language: node_js
# node_js:
#   - "node"
# install:
#   - npm install -g firebase-tools
# script:
#   - echo "deployin"
# after_success:
#   - firebase deploy --token $FIREBASE_TOKEN
