language: node_js
deploy:
  provider: firebase
  token:
    secure: "KX+z1jPDVKHQJArfjN54KA02N7HCOoIk/dHvo91c8LNnN6UuGWBIeU4BQx0qn3cS5siavwjcb7NAnzkqawzzeIoFaoA7Xg8MvWxOTrNTJm0YPozm4MvlWux9DsREpn82yxNQAZky6gReCOPlMBKVfWKXrHhTWH85T8PPiov/aaHdOmUmc1AHOVHdTvtAnPM6XhRM2hLxPiyBj18swYl1gQaBolc0Dht66L84SBd8yTpGL7mAlnGp8eXjVA1b38DeNtNOaMushNalVIuLDQkhi/99ZNzmFlN9CBt4rQCkG66Z7NBfbE4NrPyoKhEeoJdWX8FiTlzqlcJjPk7pxKSqfkmRIHjupohUZhNwRr1Drt6THVBTLMAv6AmjWHiA9ehwwDkIYM1z0QFjBE9OFpEgHIuQCEUMBzL3WzwFb8VKnD/+tAF0STe9PDWjJiy5JaqewHIUUbYcrd0XmAHXXzGI1fnad+tk7Sap+pRnEK1slndziIHY/ekEX8mLCvDr+bmF8awl4zQmHaDmoRKDU9nJI56ScE5qMlSFDnU9jfBNTyvd0AzEIaiPHGnnhwmo5SzQS+hhElpNzaKHcRhVxxNaS1QoLtWvpm/jPLJFWo+s1TUOW6W7vBZrVlZhHtZzrHkSTjUVt8eDdHK9erVrOC+UJBAJC6rV7uVV804GyT80Y/4="
# node_js:
#   - "node"
# install:
#   - npm install -g firebase-tools
# script:
#   - echo "deployin"
# after_success:
#   - firebase deploy --token $FIREBASE_TOKEN
