language: node_js
node_js:
  - "node"
install:
  - npm install -g firebase-tools
script:
  - echo "deployin"
after_success:
  - firebase deploy --token "03exYO-TXA9lRCgYIARAAGAMSNwF-L9IrobQAi4OcbknwQaRNoAEcX2dgCrIEwyrkgTAyAaHIXEZ_fS8psSTBIL9RZE-u2TmvlqY"
