language: node_js
node_js:
  - "node"
 install:
  - npm install -g firebase-tools
script:
  - echo "deployin"
after_success:
  - firebase deploy --token $FIREBASE_TOKEN

# language: node_js
# node_js:
#   - "11.0"
# branches:
#   only:
#     - master
# before_script:
#   - echo "trying to deploy"
# script:
#   - npm install -g firebase-tools
#   - npm run build
# deploy:
#   skip_cleanup: true
#   provider: firebase
#   token:
#     secure: "1//03WhXS100VMBOCgYIARAAGAMSNwF-L9IrGil4oyjk7F3tVncgDa5_Yj_c_CuNCaIukD6penPlVCnfvXUEPDzGQQviQLcpP2ltehM"
